import Link from "next/link";

export function GlossaireIaEn() {
  return (
    <>
      <p>
        AI, LLM, prompt, hallucination, agent, token… The vocabulary of AI can
        feel like a foreign language. Here are 20 terms explained simply, one
        sentence each, so you never feel lost again.
      </p>

      <h2>The basics</h2>
      <ul>
        <li>
          <strong>AI (artificial intelligence)</strong>: a program capable of
          performing tasks that normally require human intelligence.
        </li>
        <li>
          <strong>Generative AI</strong>: an AI that creates content (text,
          images, audio) rather than simply classifying or predicting.
        </li>
        <li>
          <strong>LLM (large language model)</strong>: the engine behind
          ChatGPT and its peers, trained on massive amounts of text.
        </li>
        <li>
          <strong>ChatGPT / Claude / Gemini / Le Chat</strong>: conversational
          assistants built on LLMs.
        </li>
      </ul>

      <h2>When you use it</h2>
      <ul>
        <li>
          <strong>Prompt</strong>: the message you write to an AI to ask it for
          something.
        </li>
        <li>
          <strong>Token</strong>: a fragment of a word. AI reads and writes in
          tokens, not letters.
        </li>
        <li>
          <strong>Context</strong>: everything the AI &ldquo;keeps in mind&rdquo;
          during the current conversation.
        </li>
        <li>
          <strong>Hallucination</strong>: when an AI makes up false information
          and presents it as fact.
        </li>
        <li>
          <strong>AI agent</strong>: an AI that does more than answer, chaining
          actions together to reach a goal.
        </li>
      </ul>

      <h2>Behind the scenes</h2>
      <ul>
        <li>
          <strong>Training</strong>: the phase where the model learns from
          data.
        </li>
        <li>
          <strong>Training data</strong>: the texts and images the model
          learned from.
        </li>
        <li>
          <strong>Model</strong>: the trained &ldquo;brain&rdquo; that you
          then use.
        </li>
        <li>
          <strong>Open source</strong>: a model whose inner workings are public
          and reusable (Mistral offers some).
        </li>
        <li>
          <strong>Multimodal</strong>: an AI that understands multiple formats
          (text + image + audio).
        </li>
      </ul>

      <h2>Where the debate is</h2>
      <ul>
        <li>
          <strong>Bias</strong>: prejudices present in the data, which the AI
          can reproduce.
        </li>
        <li>
          <strong>Deepfake</strong>: fake content (voice, video) generated by
          AI, sometimes used in scams.
        </li>
        <li>
          <strong>EU AI Act</strong>: the European regulation that governs how
          AI can be used.
        </li>
        <li>
          <strong>GDPR</strong>: the European data protection rules, which
          apply to AI too.
        </li>
        <li>
          <strong>Sovereignty</strong>: the idea of keeping control (and the
          data) on European soil.
        </li>
        <li>
          <strong>Prompt injection</strong>: a technique for tricking an AI by
          slipping it hidden instructions.
        </li>
      </ul>

      <h2>What now?</h2>
      <p>
        Knowing the words is the first step to losing the fear. To put it into
        practice, test your reflexes with the{" "}
        <Link href="/formations/quiz">free quiz</Link>, or learn how to{" "}
        <Link href="/fr/blog/comment-ecrire-un-prompt">write a good prompt</Link>
        . And to go further, our{" "}
        <Link href="/formations">online courses</Link> guide you step by
        step.
      </p>
    </>
  );
}
